"""Human-readable explanation generation for VibeBench runs."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from vibebench.paths import config_dir
from vibebench.pr_comment import as_dict, as_list, inline_code, text
from vibebench.report import ReportError, load_metrics, recommendation_for

EXPLANATION_FILENAME = "explain.md"


@dataclass(frozen=True)
class ExplainResult:
    """Result of generating a run explanation."""

    run_dir: Path
    output_path: Path | None
    markdown: str
    recommendation: str


def generate_explanation(
    project_root: Path,
    run_dir: Path | None = None,
    output_path: Path | None = None,
    *,
    write: bool = True,
) -> ExplainResult:
    """Generate a Markdown explanation for a VibeBench run."""
    selected_run_dir = (run_dir or find_latest_valid_run(project_root)).resolve()
    try:
        metrics = load_metrics(selected_run_dir)
    except json.JSONDecodeError as exc:
        message = f"metrics.json in {selected_run_dir} is not valid JSON."
        raise ReportError(message) from exc

    recommendation = recommendation_for(metrics)
    selected_output_path = output_path.resolve() if output_path is not None else None
    if write:
        selected_output_path = selected_output_path or (
            selected_run_dir / EXPLANATION_FILENAME
        )

    markdown = render_markdown(
        metrics,
        selected_run_dir,
        generated_output=selected_output_path if write else None,
    )

    if write and selected_output_path is not None:
        selected_output_path.parent.mkdir(parents=True, exist_ok=True)
        selected_output_path.write_text(markdown, encoding="utf-8")

    return ExplainResult(
        run_dir=selected_run_dir,
        output_path=selected_output_path,
        markdown=markdown,
        recommendation=recommendation,
    )


def find_latest_valid_run(project_root: Path) -> Path:
    """Return the latest run directory containing metrics.json."""
    runs_dir = config_dir(project_root) / "runs"
    if not runs_dir.exists():
        raise ReportError("No VibeBench runs found. Run 'vibebench check' first.")

    run_dirs = sorted(
        path
        for path in runs_dir.iterdir()
        if path.is_dir() and path.joinpath("metrics.json").exists()
    )
    if not run_dirs:
        raise ReportError("No valid VibeBench runs found. Run 'vibebench check' first.")
    return run_dirs[-1]


def render_markdown(
    metrics: dict[str, Any],
    run_dir: Path,
    generated_output: Path | None = None,
) -> str:
    """Render a Markdown explanation for a VibeBench metrics payload."""
    project_name = text(metrics.get("project_name", "Unknown project"))
    created_at = text(metrics.get("created_at", "Unknown time"))
    status = text(metrics.get("overall_status", "unknown"))
    score = text(metrics.get("score", 0))
    risk_level = text(metrics.get("risk_level", "unknown"))
    commands = as_list(metrics.get("command_results"))
    diff = as_dict(metrics.get("diff_analysis"))
    findings = as_list(metrics.get("risk_findings"))
    recommendation = recommendation_for(metrics)

    sections = [
        "# VibeBench Explanation",
        "",
        "## Summary",
        "",
        f"- **Project:** {project_name}",
        f"- **Created at:** {created_at}",
        f"- **Overall status:** {status}",
        f"- **VibeScore:** {score}",
        f"- **Risk level:** {risk_level}",
        f"- **Run directory:** `{inline_code(run_dir)}`",
        "",
        "## Command Results",
        "",
        command_explanation(commands),
        "",
        "## Git Diff Risk",
        "",
        diff_explanation(diff),
        "",
        "## Risk Findings",
        "",
        findings_explanation(findings),
        "",
        "## Suggested Next Actions",
        "",
        next_actions(metrics, commands, findings, recommendation),
        "",
        "## Artifacts",
        "",
        artifacts_section(run_dir, generated_output),
        "",
        "Generated by VibeBench Arena. Codex writes code. VibeBench verifies it.",
        "",
    ]
    return "\n".join(sections)


def command_explanation(commands: list[Any]) -> str:
    """Explain command results in plain language."""
    if not commands:
        return "No configured commands were recorded for this run."

    lines = []
    failed_count = 0
    for command in commands:
        item = as_dict(command)
        status = text(item.get("status", "unknown"))
        command_text = text(item.get("command", ""))
        exit_code = text(item.get("exit_code", ""))
        group = text(item.get("group", ""))
        if status == "passed":
            lines.append(
                f"- `{inline_code(command_text)}` ({group}) passed with exit code "
                f"{exit_code}."
            )
        else:
            failed_count += 1
            lines.append(
                f"- `{inline_code(command_text)}` ({group}) failed with exit code "
                f"{exit_code}. Inspect `check.log` for stdout/stderr, then rerun "
                "the command locally after fixing the issue."
            )

    if failed_count:
        lines.append("")
        lines.append(
            "At least one configured command failed, so this run should not be "
            "shipped until the failure is resolved."
        )
    return "\n".join(lines)


def diff_explanation(diff: dict[str, Any]) -> str:
    """Explain Git diff risk counts."""
    if not diff:
        return "No Git diff analysis was recorded for this run."

    git_available = bool(diff.get("git_available", False))
    if not git_available:
        warnings = as_list(diff.get("warnings"))
        warning_text = (
            f" Warnings: {', '.join(text(item) for item in warnings)}"
            if warnings
            else ""
        )
        return f"Git diff analysis was not available for this run.{warning_text}"

    changed_files = int(diff.get("changed_file_count", 0) or 0)
    patch_lines = int(diff.get("total_patch_lines", 0) or 0)
    added_lines = int(diff.get("total_added_lines", 0) or 0)
    deleted_lines = int(diff.get("total_deleted_lines", 0) or 0)

    if changed_files == 0 and patch_lines == 0:
        return (
            "No uncommitted Git diff was detected. Changed files and patch lines "
            "are both zero."
        )

    return "\n".join(
        [
            f"- Changed files: {changed_files}",
            f"- Added lines: {added_lines}",
            f"- Deleted lines: {deleted_lines}",
            f"- Total patch lines: {patch_lines}",
            f"- Test files changed: {len(as_list(diff.get('test_files_changed')))}",
            f"- Tests deleted: {len(as_list(diff.get('tests_deleted')))}",
            "- Forbidden paths touched: "
            f"{len(as_list(diff.get('forbidden_paths_touched')))}",
            "- Secret-like files touched: "
            f"{len(as_list(diff.get('secret_like_files_touched')))}",
            f"- Lockfiles changed: {len(as_list(diff.get('lockfiles_changed')))}",
        ]
    )


def findings_explanation(findings: list[Any]) -> str:
    """Explain risk findings and known remediation hints."""
    if not findings:
        return "No risk findings detected."

    lines = []
    for finding in findings:
        item = as_dict(finding)
        severity = text(item.get("severity", "unknown"))
        code = text(item.get("code", "unknown"))
        message = text(item.get("message", ""))
        paths = [text(path) for path in as_list(item.get("paths"))]
        path_text = ", ".join(f"`{inline_code(path)}`" for path in paths)
        if not path_text:
            path_text = "No paths recorded."
        lines.append(f"- **{severity}** `{inline_code(code)}`: {message}")
        lines.append(f"  - Evidence: {path_text}")
        lines.append(f"  - Explanation: {finding_remediation(code)}")
    return "\n".join(lines)


def finding_remediation(code: str) -> str:
    """Return a remediation hint for a risk finding code."""
    remediations = {
        "forbidden_paths_touched": (
            "Protected or sensitive paths changed. Review the change carefully "
            "or revert it before shipping."
        ),
        "secret_like_files_touched": (
            "Confirm that no credentials, private keys, API tokens, or passwords "
            "are being committed."
        ),
        "tests_deleted": (
            "Deleted tests reduce safety. Restore the tests or document why the "
            "deletion is intentional."
        ),
        "lockfiles_changed": (
            "Dependency lockfile changes need careful review because they can "
            "change installed code."
        ),
        "large_patch": (
            "The patch is large. Split it into smaller changes or review it more "
            "carefully before shipping."
        ),
        "test_files_changed": (
            "Tests changed. Ensure the tests still match the intended behavior."
        ),
    }
    return remediations.get(
        code,
        "Review this finding and affected paths carefully before shipping.",
    )


def next_actions(
    metrics: dict[str, Any],
    commands: list[Any],
    findings: list[Any],
    recommendation: str,
) -> str:
    """Render suggested next actions for the run."""
    failed_commands = [
        as_dict(command)
        for command in commands
        if text(as_dict(command).get("status", "")) != "passed"
    ]
    if not failed_commands and not findings:
        return (
            "This run looks safe to review and ship, assuming the behavior is "
            "correct."
        )

    actions = [recommendation]
    for command in failed_commands:
        command_text = text(command.get("command", ""))
        actions.append(
            f"Rerun `{inline_code(command_text)}` locally and inspect `check.log` "
            "for captured stdout/stderr."
        )
    if findings:
        actions.append(
            "Review each risk finding, confirm the affected paths are expected, "
            "and resolve high or critical findings before shipping."
        )
    if text(metrics.get("overall_status", "")) == "failed":
        actions.append("Do not ship until the failed status is resolved.")
    return "\n".join(f"- {action}" for action in actions)


def artifacts_section(run_dir: Path, generated_output: Path | None = None) -> str:
    """List known run artifacts and whether they exist."""
    artifact_paths = [
        run_dir / "metrics.json",
        run_dir / "check.log",
        run_dir / "report" / "index.html",
        run_dir / "pr-comment.md",
        run_dir / EXPLANATION_FILENAME,
        run_dir / "github-step-summary.md",
        run_dir / "gate-summary.md",
        run_dir / "compare.md",
    ]
    lines = []
    generated_output = generated_output.resolve() if generated_output else None
    for artifact_path in artifact_paths:
        artifact_path = artifact_path.resolve()
        status = (
            "available"
            if artifact_path.exists() or artifact_path == generated_output
            else "not generated"
        )
        relative_path = artifact_path.relative_to(run_dir)
        lines.append(f"- `{inline_code(relative_path)}` ({status})")

    if generated_output and not generated_output.is_relative_to(run_dir):
        lines.append(f"- `{inline_code(generated_output)}` (available)")
    return "\n".join(lines)
