"""GitHub Actions step summary generation for VibeBench runs."""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from vibebench.pr_comment import (
    as_dict,
    as_list,
    cell,
    findings_section,
    format_duration,
    inline_code,
    risk_icon,
    status_icon,
    text,
)
from vibebench.report import find_latest_run, load_metrics

SUMMARY_FILENAME = "github-step-summary.md"


def generate_github_summary(project_root: Path, run_dir: Path | None = None) -> Path:
    """Write a GitHub Actions step summary and return the output path."""
    selected_run_dir = (run_dir or find_latest_run(project_root)).resolve()
    metrics = load_metrics(selected_run_dir)
    summary = render_markdown(metrics, selected_run_dir)
    env_path = os.environ.get("GITHUB_STEP_SUMMARY")

    if env_path:
        output_path = Path(env_path).resolve()
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with output_path.open("a", encoding="utf-8") as handle:
            handle.write(summary)
        return output_path

    output_path = selected_run_dir / SUMMARY_FILENAME
    output_path.write_text(summary, encoding="utf-8")
    return output_path


def render_markdown(metrics: dict[str, Any], run_dir: Path) -> str:
    """Render a GitHub Actions step summary as Markdown."""
    project_name = text(metrics.get("project_name", "Unknown project"))
    created_at = text(metrics.get("created_at", "Unknown time"))
    status = text(metrics.get("overall_status", "unknown"))
    score = text(metrics.get("score", 0))
    risk_level = text(metrics.get("risk_level", "unknown"))
    commands = as_list(metrics.get("command_results"))
    diff = as_dict(metrics.get("diff_analysis"))
    findings = as_list(metrics.get("risk_findings"))

    sections = [
        "# VibeBench Summary",
        "",
        f"- **Overall status:** {status_icon(status)} {status}",
        f"- **VibeScore:** {score}",
        f"- **Risk level:** {risk_icon(risk_level)} {risk_level}",
        f"- **Project:** {project_name}",
        f"- **Created at:** {created_at}",
        "",
        "## Command Results",
        "",
        command_table(commands),
        "",
        "## Git Diff Risk",
        "",
        diff_summary(diff, findings),
        "",
        "## Risk Findings",
        "",
        findings_section(findings),
        "",
        "## Artifacts",
        "",
        artifacts_section(run_dir),
        "",
        "Generated by VibeBench Arena — Codex writes code. VibeBench verifies it.",
        "",
    ]
    return "\n".join(sections)


def command_table(commands: list[Any]) -> str:
    """Render command results as a Markdown table."""
    rows = [
        "| Group | Command | Status | Exit Code | Duration |",
        "| --- | --- | --- | --- | --- |",
    ]
    if not commands:
        rows.append("| - | - | - | - | - |")
        return "\n".join(rows)

    for command in commands:
        item = as_dict(command)
        status = text(item.get("status", "unknown"))
        rows.append(
            "| "
            f"{cell(item.get('group', ''))} | "
            f"`{inline_code(item.get('command', ''))}` | "
            f"{status_icon(status)} {cell(status)} | "
            f"{cell(item.get('exit_code', ''))} | "
            f"{cell(format_duration(item.get('duration_seconds', 0)))} |"
        )
    return "\n".join(rows)


def diff_summary(diff: dict[str, Any], findings: list[Any]) -> str:
    """Render Git diff risk counts."""
    return "\n".join(
        [
            f"- **Changed files:** {text(diff.get('changed_file_count', 0))}",
            f"- **Added lines:** {text(diff.get('total_added_lines', 0))}",
            f"- **Deleted lines:** {text(diff.get('total_deleted_lines', 0))}",
            f"- **Patch lines:** {text(diff.get('total_patch_lines', 0))}",
            f"- **Tests deleted:** {len(as_list(diff.get('tests_deleted')))}",
            "- **Forbidden paths touched:** "
            f"{len(as_list(diff.get('forbidden_paths_touched')))}",
            "- **Secret-like files touched:** "
            f"{len(as_list(diff.get('secret_like_files_touched')))}",
            f"- **Lockfiles changed:** {len(as_list(diff.get('lockfiles_changed')))}",
            f"- **Risk findings:** {len(findings)}",
        ]
    )


def artifacts_section(run_dir: Path) -> str:
    """Render known VibeBench artifact paths for the run."""
    artifact_paths = [
        run_dir / "metrics.json",
        run_dir / "check.log",
        run_dir / "manifest.json",
        run_dir / "report" / "index.html",
        run_dir / "pr-comment.md",
        run_dir / "explain.md",
        run_dir / "vibebench-bundle.zip",
        run_dir / "export.json",
        run_dir / "badge.json",
        run_dir / "badge.md",
        run_dir / "status-block.md",
        run_dir / "trend.md",
        run_dir / "trend.json",
        run_dir / "gate-summary.md",
    ]
    lines = []
    for artifact_path in artifact_paths:
        status = "available" if artifact_path.exists() else "not generated"
        relative_path = artifact_path.relative_to(run_dir)
        lines.append(f"- `{inline_code(relative_path)}` ({status})")
    return "\n".join(lines)
