"""PR-ready Markdown comment generation for VibeBench runs."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from vibebench.report import find_latest_run, load_metrics, recommendation_for

MAX_FINDINGS = 10


def generate_pr_comment(project_root: Path, run_dir: Path | None = None) -> Path:
    """Generate pr-comment.md for a run and return its path."""
    selected_run_dir = (run_dir or find_latest_run(project_root)).resolve()
    metrics = load_metrics(selected_run_dir)
    output_path = selected_run_dir / "pr-comment.md"
    output_path.write_text(render_markdown(metrics), encoding="utf-8")
    return output_path


def render_markdown(metrics: dict[str, Any]) -> str:
    """Render a concise Markdown summary for a pull request comment."""
    project_name = text(metrics.get("project_name", "Unknown project"))
    created_at = text(metrics.get("created_at", "Unknown time"))
    status = text(metrics.get("overall_status", "unknown"))
    score = text(metrics.get("score", 0))
    risk_level = text(metrics.get("risk_level", "unknown"))
    commands = as_list(metrics.get("command_results"))
    diff = as_dict(metrics.get("diff_analysis"))
    findings = as_list(metrics.get("risk_findings"))
    recommendation = recommendation_for(metrics)

    sections = [
        "## VibeBench Check",
        "",
        f"- **Status:** {status_icon(status)} {status}",
        f"- **VibeScore:** {score}",
        f"- **Risk:** {risk_icon(risk_level)} {risk_level}",
        f"- **Project:** {project_name}",
        f"- **Created at:** {created_at}",
        "",
        "### Command Results",
        "",
        command_table(commands),
        "",
        "### Git Diff Risk Summary",
        "",
        diff_summary(diff, findings),
        "",
        "### Risk Findings",
        "",
        findings_section(findings),
        "",
        "### Recommendation",
        "",
        recommendation,
        "",
        "_Generated by VibeBench Arena — Codex writes code. VibeBench verifies it._",
        "",
    ]
    return "\n".join(sections)


def command_table(commands: list[Any]) -> str:
    """Render command results as a Markdown table."""
    rows = [
        "| Group | Command | Status | Exit Code | Duration |",
        "| --- | --- | --- | --- | --- |",
    ]
    if not commands:
        rows.append("| - | - | - | - | - |")
        return "\n".join(rows)

    for command in commands:
        item = as_dict(command)
        rows.append(
            "| "
            f"{cell(item.get('group', ''))} | "
            f"`{inline_code(item.get('command', ''))}` | "
            f"{status_icon(text(item.get('status', 'unknown')))} "
            f"{cell(item.get('status', 'unknown'))} | "
            f"{cell(item.get('exit_code', ''))} | "
            f"{cell(format_duration(item.get('duration_seconds', 0)))} |"
        )
    return "\n".join(rows)


def diff_summary(diff: dict[str, Any], findings: list[Any]) -> str:
    """Render Git diff summary bullets."""
    rows = [
        f"- **Changed files:** {text(diff.get('changed_file_count', 0))}",
        f"- **Added lines:** {text(diff.get('total_added_lines', 0))}",
        f"- **Deleted lines:** {text(diff.get('total_deleted_lines', 0))}",
        f"- **Patch lines:** {text(diff.get('total_patch_lines', 0))}",
        f"- **Tests deleted:** {len(as_list(diff.get('tests_deleted')))}",
        "- **Forbidden paths touched:** "
        f"{len(as_list(diff.get('forbidden_paths_touched')))}",
        "- **Secret-like files touched:** "
        f"{len(as_list(diff.get('secret_like_files_touched')))}",
        f"- **Lockfiles changed:** {len(as_list(diff.get('lockfiles_changed')))}",
        f"- **Risk findings:** {len(findings)}",
    ]
    return "\n".join(rows)


def findings_section(findings: list[Any]) -> str:
    """Render up to ten risk findings."""
    if not findings:
        return "No risk findings detected."

    lines: list[str] = []
    for finding in findings[:MAX_FINDINGS]:
        item = as_dict(finding)
        severity = text(item.get("severity", "info"))
        code = text(item.get("code", "unknown"))
        message = truncate(text(item.get("message", "")), 220)
        paths = as_list(item.get("paths"))
        line = f"- **{severity}** `{inline_code(code)}`: {message}"
        if paths:
            rendered_paths = ", ".join(
                f"`{inline_code(truncate(text(path), 120))}`" for path in paths[:5]
            )
            if len(paths) > 5:
                rendered_paths = f"{rendered_paths}, +{len(paths) - 5} more"
            line = f"{line} ({rendered_paths})"
        lines.append(line)

    remaining = len(findings) - MAX_FINDINGS
    if remaining > 0:
        lines.append(f"...and {remaining} more findings.")
    return "\n".join(lines)


def status_icon(status: str) -> str:
    """Return the icon for a status value."""
    return "✅" if status == "passed" else "❌"


def risk_icon(risk_level: str) -> str:
    """Return the icon for a risk level."""
    return {
        "low": "🟢",
        "medium": "🟡",
        "high": "🟠",
        "critical": "🔴",
    }.get(risk_level, "⚪")


def format_duration(value: object) -> str:
    """Format seconds for display."""
    try:
        return f"{float(value):.3f}s"
    except (TypeError, ValueError):
        return text(value)


def cell(value: object) -> str:
    """Escape Markdown table cell delimiters."""
    return text(value).replace("|", "\\|").replace("\n", " ")


def inline_code(value: object) -> str:
    """Make text safe inside Markdown inline code."""
    return text(value).replace("`", "\\`").replace("|", "\\|").replace("\n", " ")


def truncate(value: str, limit: int) -> str:
    """Keep generated comments concise."""
    if len(value) <= limit:
        return value
    return f"{value[: limit - 3]}..."


def as_dict(value: object) -> dict[str, Any]:
    """Return value as a dict if possible."""
    return value if isinstance(value, dict) else {}


def as_list(value: object) -> list[Any]:
    """Return value as a list if possible."""
    return value if isinstance(value, list) else []


def text(value: object) -> str:
    """Convert dynamic values to text."""
    if value is None:
        return ""
    return str(value)
